// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWj3mA1RhMZU0f6EBfYa6sCZbcNqZpWcU',
    appId: '1:721262082922:web:caf18e649a86af24a30313',
    messagingSenderId: '721262082922',
    projectId: 'vodomont-pantic',
    authDomain: 'vodomont-pantic.firebaseapp.com',
    storageBucket: 'vodomont-pantic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8hiXYcq9p7xy3GsW1W5Y4U03hO9bqSpI',
    appId: '1:721262082922:android:4713c75f4eb35218a30313',
    messagingSenderId: '721262082922',
    projectId: 'vodomont-pantic',
    storageBucket: 'vodomont-pantic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdysfMsf22RmClVctTBb2MGdDGDkOtMs',
    appId: '1:721262082922:ios:75b6737a026b4071a30313',
    messagingSenderId: '721262082922',
    projectId: 'vodomont-pantic',
    storageBucket: 'vodomont-pantic.firebasestorage.app',
    iosBundleId: 'com.example.vodomontPantic',
  );
}
